// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProjectInfo.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Build source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.String.Recipes
{
    using global::System.Reflection;

    /// <summary>
    /// Project-related information.
    /// </summary>
    public static class ProjectInfo
    {
        /// <summary>
        /// The namespace used by types in this project.
        /// </summary>
        public static readonly string Namespace = typeof(ProjectInfo).Namespace;

        /// <summary>
        /// The assembly produced by this project.
        /// </summary>
        public static readonly Assembly Assembly = typeof(ProjectInfo).Assembly;
    }
}